POST http://localhost:3003/api/blogs/
Content-Type : application/json

{
  "title": "prueba",
  "author": "alex",
  "url": "http://localhost:3003/api/blogs/",
  "likes": "13"
}
###
GET http://localhost:3003/api/blogs/
Content-Type: application/json

{}

###
GET http://localhost:3003/api/blogs/gabriela
Content-Type: application/json

{}

###
DELETE http://localhost:3003/api/blogs/6394c3df83fbe72694d15cec
Content-Type: application/json

{}
###
PUT http://localhost:3003/api/blogs/6394caa7a091063995a5d4bc
Content-Type: application/json

{
  "name": "Alex",
  "number": "1315431131"
}

###
GET http://localhost:3003/api/info/
Content-Type: application/json

{}